### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Spacekase321** [kroma-network/go-ethereum#60]
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by 0xHansLee** [comment]
Hello @Spacekase321,

Could you fill out the form w.r.t the errors you are struggling with?

**Comment by Spacekase32** [comment]
I dunno what to do

**Comment by 0xHansLee** [comment]
I'll close this issue. If you have any specific issues, please create an issue again with detailed description.
If you wanna run a Kroma node or validator, please check the below instructions.
https://docs.kroma.network/developers/running-nodes-on-kroma
